name: Deploy Vue.js to GitHub Pages

on:
  push:
    branches:
      - main  # La rama desde la que quieres desplegar

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Versión correcta de Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Se usa el token para autenticación
          publish_dir: ./dist  # Directorio donde se genera la build
